# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMh5SnSpevCFwFn2QgN_5n5I5S8uFMVo
"""

{
	"@context": {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ex": "http://example.org/",
    "Person": "ex:Person",
    "fullName": "rdfs:label",
    "hometown": "ex:hometown",
    "age": "ex:age",
    "almaMater": "ex:almaMater",
    "parent": "ex:parent",
    "father": "ex:father",
    "mother": "ex:mother",
    "subjects": "ex:subjects",
    "subject": "ex:subject",
    "subjectName":"rdfs:label",
    "description":"rdfs:description",
    "teacher":"ex:teacher"
  },

  "@id": "mariacabanes",
  "@type": "Person",
  "full Name": "María Cabanes Alañón",
  "hometown": "Ciudad Real",
  "age": "23",
  "almaMater": "Universidad Politécnica de Madrid",
  "parents": {
    "mother": "Toya",
    "father": "Jaime"
  },
  "subjectsThisYear": [
    {
      "name": "Statistical Data Analysis",
      "teacher": "Arminda Moreno",
      "description": "The course is intended to be a non-exhaustive survey of techniques to convert multivariate data into useful information so that good decisions can be made."
    },
    {
      "name": "Data Visualization",
      "teacher": "Pablo Toharia Rabasco",
      "description": "This course will allow the student to gain the fundamentals for the visualization of all kinds of information."
    },
    {
      "name": "Data Processes",
      "teacher": "Pablo Toharia Rabasco",
      "description": "This course focuses on the importance of data for organizations, particularly in supporting decision-making through knowledge extraction from databases."
    },
    {
      "name": "Big Data",
      "teacher": "Antonio Latorre de la Fuente",
      "description": "This course will allow the student to gain the fundamentals for the analytical visualization of large volumes of data."
    },
    {
      "name": "Intelligent Systems",
      "teacher": "Martín Molina",
      "description": "This course covers intelligent systems that utilize AI methods for problem-solving, starting with machine learning techniques and algorithms, followed by knowledge representation, language technologies, and ethics in AI."
    },
    {
      "name": "Open data and knowledge graphs",
      "teacher": "Oscar Corcho",
      "description": "This course focuses on the foundations of Linked Data and the Semantic Web, covering W3C recommendations (RDF, SPARQL, OWL) and methodologies for generating and publishing Linked Data."
    },
    {
      "name": "Introduction to Innovation and Entrepenaurship Management",
      "teacher": "Alberto Tejero",
      "description": "Idea generation, technology-based entrepreneurship, marketing and markets, organization and project management, new product and process development, entrepreneurial finance, human resource development."
    },
    {
      "name": "Machine Learning",
      "teacher": ["Pedro Larrañaga", "Concha Bielza"],
      "description": "This course focuses on transforming data into actionable insights through machine learning"
    }
  ]
}