-- Query 1
SELECT DISTINCT ?class
WHERE {
  ?instance a ?class .
}
LIMIT 10

-- Query 2
SELECT DISTINCT ?property
WHERE {
  ?s ?property ?o .
}
LIMIT 10

-- Query 3
SELECT DISTINCT ?trips
WHERE {
  ?trips a <https://BiciMad.es/ontology#BikeTrip> .
}
LIMIT 10

-- Query 4
SELECT DISTINCT ?stations
WHERE {
  ?stations a <https://BiciMad.es/ontology#BikeStation> .
}
LIMIT 10

-- Query 5
PREFIX bici: <https://BiciMad.es/ontology#>
PREFIX schema: <https://schema.org/>

SELECT ?station
WHERE {
  ?station a bici:BikeStation .
  ?station schema:address ?address .
  ?address schema:containedInPlace <http://www.BiciMad.es/entity/Place/Centro> .
}
LIMIT 10

-- Query 6
PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?freePlace ?postalCode
WHERE {
    ?freePlace a schema:Place .
    ?freePlace schema:address ?address .
    ?address schema:postalCode ?postalCode .
    ?freePlace schema:id ?freePlaceId . 
    FILTER(?postalCode= "28050"^^xsd:int) 
}
LIMIT 10

-- Query 7
PREFIX schema: <https://schema.org/>
PREFIX bici: <https://BiciMad.es/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?trips ?stationName ?unlockDate ?lockDate ?bikeId ?stationId
WHERE {
  ?trips schema:itinerary ?station .
  ?station schema:identifier ?stationId .
  ?station schema:address ?address .
  ?address schema:streetAddress ?stationName .
  ?trips schema:departureTime ?unlockDate .
  ?trips schema:arrivalTime ?lockDate .
  ?trips bici:bikeIdentifier ?bikeId .
  
  FILTER(?stationId = "Station170"^^xsd:string)
}
LIMIT 10

-- Query 8
PREFIX schema: <https://schema.org/>
PREFIX bici: <https://BiciMad.es/ontology#>
SELECT ?trips ?stationName ?unlockDate ?bikeId
WHERE {
  ?trips schema:tripOrigin ?station .
  ?station schema:identifier ?stationId .
  ?station schema:address ?address .
  ?address schema:streetAddress ?stationName .
  ?trips schema:departureTime ?unlockDate .
  ?trips bici:bikeIdentifier ?bikeId .

  FILTER (SUBSTR(STR(?unlockDate), 1, 10) = "2023-02-07")
}
LIMIT 10

-- Query 9
PREFIX bici: <https://BiciMad.es/ontology#>
SELECT ?trips ?station ?unlockDate ?lockDate ?bikeId
WHERE {
  ?trips bici:hasLockDock ?lockDock .
  ?trips schema:tripOrigin ?station .
  ?trips schema:departureTime ?unlockDate .
  ?trips schema:arrivalTime ?lockDate .
  ?trips bici:bikeIdentifier ?bikeId .

  FILTER (SUBSTR(STR(?lockDock), 1, 2) = "24")
}
LIMIT 10

-- Query 10
PREFIX bici: <https://BiciMad.es/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?trips ?station ?unlockDate ?lockDate ?bikeId
WHERE {
  ?trips schema:tripOrigin ?station .
  ?trips schema:departureTime ?unlockDate .
  ?trips schema:arrivalTime ?lockDate .
  ?trips bici:bikeIdentifier ?bikeId .

  FILTER (?bikeId = "33"^^xsd:integer)
}
LIMIT 10

