# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nBJ0R4Kc6_inUy3hxn2HwpTu-3g6Gbh

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.namespace import OWL

query_1 = """
  PREFIX vcard: <http://www.w3.org/2001/vcard-rdf/3.0#>

  SELECT ?person ?givenName ?fullName WHERE
  {
    ?person a data:Person .
    OPTIONAL {?person vcard:Given ?givenName .}
    OPTIONAL {?person vcard:FN ?fullName .}
  }
"""

query_2 = """
  PREFIX vcard: <http://www.w3.org/2001/vcard-rdf/3.0#>

  SELECT ?person WHERE
  {
    ?person a data:Person .
    ?person vcard:Given ?inputGivenName .
    ?person vcard:FN ?inputFullName .
  }
"""

query_3 = """
  SELECT ?s ?p ?o WHERE
  {
    ?s ?p ?o .
  }
"""

for row_g1_q1 in g1.query(query_1, initNs={'data': URIRef("http://data.three.org#")}):
  print(f"G1 - {row_g1_q1.person} => Given name: '{row_g1_q1.givenName}'. Family name: '{row_g1_q1.fullName}'")

for row_g2_q1 in g2.query(query_1, initNs={'data': URIRef("http://data.four.org#")}):
  print(f"G2 - {row_g2_q1.person} => Given name: '{row_g2_q1.givenName}'. Family name: '{row_g2_q1.fullName}'")

for row_g1_q1 in g1.query(query_1, initNs={'data': URIRef("http://data.three.org#")}):
  for row_g2_q2 in g2.query(query_2, initNs={'data': URIRef("http://data.four.org#")}, initBindings={"inputGivenName": Literal(row_g1_q1.givenName), "inputFullName": Literal(row_g1_q1.fullName)}):
    print(f"(G2 - {row_g2_q2.person}) ≡ (G1 - {row_g1_q1.person} => Given name: '{row_g1_q1.givenName}'. Family name: '{row_g1_q1.fullName}')")
    g3.add((URIRef(row_g1_q1.person), OWL.sameAs, URIRef(row_g2_q2.person)))

for row_g3_q3 in g3.query(query_3):
  print(f"G3 - {row_g3_q3.s} {row_g3_q3.p} {row_g3_q3.o}")