# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qvNxmYqjbdAJ8hSMCg8LNL_pBuSMah3m

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

# List of all elements of class Person in graph 1
from rdflib.namespace import RDF, RDFS
ns = Namespace("http://data.org#")
vcard= Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for s,p,o in g1.triples((None, RDF.type, ns.Person)):
    for s1,p1,o1 in g1.triples((s,None,None)):
      print(s1,p1,o1)

# Completing fields with data of graph 2
for s,p,o in g2.triples((None, RDF.type, ns.Person)):
    for s1,p1,o1 in g2.triples((s, vcard.Given, None)):
        g1.add((s1,p1,o1))
    for s2,p2,o2 in g2.triples((s, vcard.Family, None)):
        g1.add((s2,p2,o2))
    for s3,p3,o3 in g2.triples((s, vcard.EMAIL, None)):
        g1.add((s3,p3,o3))

# New elements of class Person in graph 1
for s,p,o in g1.triples((None, RDF.type, ns.Person)):
    for s1,p1,o1 in g1.triples((s,None,None)):
      print(s1,p1,o1)