# Select all the locations that has a correlation with a wikidata entry

  SELECT ?StationLocation ?WikidataLink WHERE {
    ?Subject <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://mAIRdrid.org/ontology/Location>.
    ?Subject <http://www.w3.org/2000/01/rdf-schema#label> ?StationLocation.
    FILTER(LANG(?StationLocation) = "es")
    ?Subject <http://www.w3.org/2002/07/owl#sameAs> ?WikidataLink.
  }

# Select all the medition that has its unit reconciled with a WikiData entry
  SELECT ?Sensor ?WikidataLink WHERE {
    ?Subject <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://mAIRdrid.org/ontology/AirQualityMetric>.
    ?Subject <http://www.w3.org/2000/01/rdf-schema#label> ?Sensor.
    FILTER(LANG(?Sensor) = "es")
    ?Subject <http://www.w3.org/2002/07/owl#sameAs> ?WikidataLink.
  }
