# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Crlx9sQXmFZfzpDYy9_HqW5IvjY48jE

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

for s,p,o in g2:
  print(s,p,o)

for s,p,o in g1:
  print(s,p,o)

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib.namespace import RDF, RDFS
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
ns = Namespace("http://data.org#")
for s,p,o in g1.triples((None,RDF.type,ns.Person)):
  print(s)
  if g1.value(s,VCARD.Given,None) is None:
    g1.add((s,VCARD.Given,g2.value(s,VCARD.Given,None)))
  if g1.value(s,VCARD.Family,None) is None:
    g1.add((s,VCARD.Family,g2.value(s,VCARD.Family,None)))
  if g1.value(s,VCARD.EMAIL,None) is None:
    g1.add((s,VCARD.EMAIL,g2.value(s,VCARD.EMAIL,None)))
  for s,p,o in g1.triples((s,None,None)):
    print(s,p,o)