# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZCoqOLPwanqZ-FZgQHEzPpFZWj7eQQb

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import OWL,RDF
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

for s,p,o in g1:
  print(s,p,o)

for s,p,o in g2:
  print(s,p,o)

ns1 = Namespace("http://data.three.org#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
for s,p,o in g1.triples((None,RDF.type,ns1.Person)):
  #print(s,p,o)
  nicknameG1 = g1.value(s,VCARD.Given,None)
  familyNameG1= g1.value(s,VCARD.Family,None)
  if g2.value(None,VCARD.Given,nicknameG1) is not None and g2.value(None,VCARD.Family,familyNameG1) is not None:
    g3.add((s,OWL.sameAs,g2.value(None,VCARD.Given,nicknameG1)))
for s,p,o in g3:
  print(s,p,o)