# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MVXDfyLEh6BaelcLzsxuj2Pm_wIODSH3

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# RDFLib
ns = Namespace("http://somewhere#")

# Visualize the results
for s,p,o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
  print(s)

#SPARQL
from rdflib.plugins.sparql import prepareQuery
q1 = prepareQuery('''
  SELECT ?subclass WHERE {
    ?subclass rdfs:subClassOf ns:LivingThing.
  }
  ''',
  initNs = {"rdfs":RDFS, "ns":ns}
)

# Visualize the results
for r in g.query(q1):
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# RDFLib
ns = Namespace("http://somewhere#")

# Visualize the results
for s1,p1,o1 in g.triples((None, RDF.type, ns.Person)):
  print(s1)
print("-------------------------------------------------------------")
for s1,p1,o1 in g.triples((None, RDFS.subClassOf, ns.Person)):
    for s2,p2,o2 in g.triples((None, RDF.type, s1)):
        print(s2)

#SPARQL
from rdflib.plugins.sparql import prepareQuery
q1 = prepareQuery('''
  SELECT ?individual WHERE {
    ?subclass rdfs:subClassOf* ns:Person.
    ?individual rdf:type ?subclass.
  }
  ''',
  initNs = {"rdfs":RDFS, "ns":ns}
)

# Visualize the results
for r in g.query(q1):
  print(r)

"""**TASK 7.3: List all individuals of just "Person" or "Animal". You do not need to list the individuals of the subclasses of person (in SPARQL only)**

"""

# SPARQL
from rdflib.plugins.sparql import prepareQuery
q1 = prepareQuery('''
  SELECT ?individual ?property ?value
    WHERE {
        ?individual rdf:type ?class .
        ?individual ?property ?value .
        {?individual rdf:type ns:Person .}
        UNION
        {?individual rdf:type ns:Animal .}
      }

  ''',
  initNs = {"rdfs":RDFS, "ns":ns}
)

# Visualize the results
for r in g.query(q1):
  print(r[0],r[1],r[2])

"""**TASK 7.4:  List the name of the persons who know Rocky (in SPARQL only)**"""

from rdflib.namespace import FOAF
q1 = prepareQuery('''
  SELECT ?name WHERE {
    {
      ?name rdf:type ns:Person.
      ?name foaf:knows ns:RockySmith.
    }
    UNION {
      ?class rdfs:subClassOf ns:Person.
      ?name rdf:type ?class.
      ?name foaf:knows ns:RockySmith.
    }

  }
  ''',
  initNs = {"rdfs":RDFS, "ns":ns, "foaf":FOAF}
)

# Visualize the results
for r in g.query(q1):
  print(r)

"""**Task 7.5: List the name of those animals who know at least another animal in the graph (in SPARQL only)**"""

from rdflib.namespace import FOAF
q1 = prepareQuery('''
    SELECT ?name WHERE {
        ?name rdf:type ns:Animal.
        ?name foaf:knows ?otheranimal.
        ?otheranimal rdf:type ns:Animal.
    }
  ''',
  initNs = {"rdfs":RDFS, "ns":ns, "foaf":FOAF}
)

# Visualize the results
for r in g.query(q1):
  print(r)

"""**Task 7.6: List the age of all living things in descending order (in SPARQL only)**"""

from rdflib.namespace import FOAF
q1 = prepareQuery('''
    SELECT ?name ?age WHERE {
        ?name foaf:age ?age
    }
    ORDER BY DESC(?age)
  ''',
  initNs = {"rdfs":RDFS, "ns":ns, "foaf":FOAF}
)

# Visualize the results
for r in g.query(q1):
  print(r)