# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-dNlvOiISvRQEhgYZqfatHoB-5i_AQEG

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.namespace import RDF, RDFS

ns = Namespace("http://data.org#")
vcard= Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
owl = Namespace("http://www.w3.org/2002/07/owl#")

for s1, p1, o1 in g1.triples((None, vcard.Given, None)):
    for s2, p2, o2 in g2.triples((None, vcard.Given, None)):
        if o1 == o2:  # at this point the two entity s and ss have the same given name
            # print("Given name match",s,ss,o)
            for s3, p3, o3 in g1.triples((s1, vcard.Family, None)):
                for s4, p4, o4 in g2.triples((s2, vcard.Family, None)):
                    if o3 == o4:
                        # print("And family name too",s,ss,o,o1)
                        g3.add((s1, owl.sameAs, s4))

for s, p, o in g3.triples((None, None, None)):
    print(s, p, o)