# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgyA9XdrmRS-1qLlnX3nVSRAYWZSgsfx

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.plugins.sparql import prepareQuery

VCARD=Namespace('http://www.w3.org/2001/vcard-rdf/3.0#')

q1= prepareQuery('''
  SELECT DISTINCT ?Subject ?Object WHERE {
    ?Subject vcard:FN ?Object
  }
  ''',initNs={'vcard':VCARD}
)



# for r in g2.query(q1):
#   print(r.Subject)

## Buscamos G2
for r in g1.query(q1):
  print(r.Subject)
  ## Identificamos 4 individuos (sujetos abajo)

  # 'http://data.three.org#SaraJones'
  # 'http://data.three.org#JohnSmith'
  # 'http://data.three.org#JohnDoe'
  # 'http://data.three.org#HarryPotter'

## Buscamos G2

for r in g2.query(q1):
  print(r.Subject,r.Object)

  ## Identificamos 4 indivudos que son coincidos en g1
    # 'http://data.four.org#0001 Sara Jones'
    # 'http://data.four.org#0002 John Smith'
    # 'http://data.four.org#0003 Harry Potter'
    # 'http://data.four.org#0005 John Doe'

## Ahora creamos 4 entidades en g3


OWL=Namespace('http://www.w3.org/TR/owl-ref/#')

Data3=Namespace('http://data.three.org#')



g3.add((Data3.SaraJones,OWL.sameAs,Literal('http://data.four.org#0001')))

g3.add((Data3.JohnSmith,OWL.sameAs,Literal('http://data.four.org#0002')))

g3.add((Data3.JohnDoe,OWL.sameAs,Literal('http://data.four.org#0005')))

g3.add((Data3.HarryPotter,OWL.sameAs,Literal('http://data.four.org#0003')))

for s,p,o in g3:
  print(s,p,o)